language: php

php:
  - 5.4
  - 5.5
  - 5.6

env:
  - LARAVEL_VERSION="~4.2"
  - LARAVEL_VERSION="~5"

before_install:
  - sed -i s/~4.2\|\|~5/${LARAVEL_VERSION}/ composer.json
  - composer update # Use update since we'll be changing the composer.json

script:
  - vendor/bin/phpspec run